services:

    #
    # Event Dispatchers
    #
    elcodi.core.coupon.event_dispatcher.coupon:
        class: %elcodi.core.coupon.event_dispatchers.coupon.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.coupon_event_dispatcher:
        alias: elcodi.core.coupon.event_dispatcher.coupon
